version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules